/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package candproject1;

import Data.ClassData;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class Hoadon extends javax.swing.JFrame {

    /**
     * Creates new form Hoadon
     */
    public Hoadon() {
        initComponents();
        ChonSP();
//        ChonHD();
        ChonDSHD();
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    public void ChonSP() {
        try {
            Con = ClassData.ConnectDb();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from banhang.Sanpham");
            BangSP.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ChonDSHD() {
        try {
            Con = ClassData.ConnectDb();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from banhang.Danhsachhoadon");
            DSHD.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
//    public void Tinhngay()  {
//
//        String dateStart = DSHD.get;
//        String dateStop = java.time.LocalDateTime.now().toString();
//
////HH converts hour in 24 hours format (0-23), day calculation
//        SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
//
//        Date d1 = null;
//        Date d2 = null;
//
//        try {
//            d1 = format.parse(dateStart);
//            d2 = format.parse(dateStop);
//
////in milliseconds
//            long diff = d2.getTime() - d1.getTime();
//
////            long diffSeconds = diff / 1000 % 60;
////            long diffMinutes = diff / (60 * 1000) % 60;
//            long diffHours = diff / (60 * 60 * 1000) % 24;
////            long diffDays = diff / (24 * 60 * 60 * 1000);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//    }

    public void xoaHDdahuy() {
        try {
            String Mahd = Mahoadon.getText();
            String Query = "Delete from banhang.Danhsachhoadon where `Mã Hóa Đơn`=" + Mahd;
            Statement Add = Con.createStatement();
            Add.executeUpdate(Query);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
//    public void ChonHD() {
//        try {
//            Con = ClassData.ConnectDb();
//            St = Con.createStatement();
//            Rs = St.executeQuery("Select * from banhang.Hoadon");
//            Chitiethoadon.setModel(DbUtils.resultSetToTableModel(Rs));
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    public void ChonHD() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"Mã Hóa Đơn", "Mã Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"}, 0);
        Con = ClassData.ConnectDb();
        try {
            String tk = MaHD.getText();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from banhang.hoadon where `Mã Hóa Đơn` like '" + tk + "'");
            while (Rs.next()) {
                String d = Rs.getString("Mã Hóa Đơn");
                String e = Rs.getString("Mã Sản Phẩm");
                String f = Rs.getString("Số Lượng");
                String g = Rs.getString("Đơn Giá");
                String h = Rs.getString("Thành Tiền");
                model.addRow(new Object[]{d, e, f, g, h});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        Chitiethoadon.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Xoa = new javax.swing.JButton();
        Them = new javax.swing.JButton();
        Huy = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BangSP = new javax.swing.JTable();
        SoSP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GiaSP = new javax.swing.JTextField();
        Thanhtien = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MaHD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MaSP = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSHD = new javax.swing.JTable();
        themhoadon = new javax.swing.JButton();
        hoanthanhhoadon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Mahoadon = new javax.swing.JTextField();
        jDateNL = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tinhtrang = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ghichu = new javax.swing.JTextField();
        suahoadon = new javax.swing.JButton();
        xoahoadon = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        TenKhachHang = new javax.swing.JTextField();
        Timkiem2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MaHoaDonTongTien = new javax.swing.JTextField();
        in_hoa_don = new javax.swing.JButton();
        jBTTONGHD = new javax.swing.JButton();
        jTongTien = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Chitiethoadon = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 85, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 540));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 85, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("QUẢN LÝ HÓA ĐƠN");

        Xoa.setBackground(new java.awt.Color(110, 0, 0));
        Xoa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Xoa.setForeground(new java.awt.Color(255, 255, 255));
        Xoa.setText("Xóa");
        Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XoaMouseClicked(evt);
            }
        });
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Them.setBackground(new java.awt.Color(0, 85, 0));
        Them.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Them.setForeground(new java.awt.Color(255, 255, 255));
        Them.setText("Thêm");
        Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThemMouseClicked(evt);
            }
        });
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Huy.setBackground(new java.awt.Color(0, 85, 0));
        Huy.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Huy.setForeground(new java.awt.Color(255, 255, 255));
        Huy.setText("Hủy");
        Huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HuyMouseClicked(evt);
            }
        });

        Sua.setBackground(new java.awt.Color(0, 85, 0));
        Sua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sua.setForeground(new java.awt.Color(255, 255, 255));
        Sua.setText("Sửa");
        Sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuaMouseClicked(evt);
            }
        });
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BangSP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BangSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại", "Số Lượng", "Giá Tiền", "Ghi Chú"
            }
        ));
        BangSP.setRowHeight(25);
        BangSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangSPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BangSPMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(BangSP);
        if (BangSP.getColumnModel().getColumnCount() > 0) {
            BangSP.getColumnModel().getColumn(0).setMaxWidth(80);
            BangSP.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        SoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoSPActionPerformed(evt);
            }
        });
        SoSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SoSPKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 85, 0));
        jLabel8.setText("Số lượng");

        GiaSP.setEditable(false);
        GiaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiaSPActionPerformed(evt);
            }
        });
        GiaSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GiaSPKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 85, 0));
        jLabel12.setText("Thành Tiền");

        MaHD.setEditable(false);
        MaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaHDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 85, 0));
        jLabel9.setText("Mã Hóa Đơn");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 85, 0));
        jLabel7.setText("Mã Sản Phẩm");

        MaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaSPActionPerformed(evt);
            }
        });
        MaSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MaSPKeyPressed(evt);
            }
        });

        DSHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Tên Khách Hàng", "Ngày Lập", "Tình trạng", "Ghi Chú"
            }
        ));
        DSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSHDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DSHDMousePressed(evt);
            }
        });
        DSHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DSHDKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(DSHD);

        themhoadon.setBackground(new java.awt.Color(0, 85, 0));
        themhoadon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        themhoadon.setForeground(new java.awt.Color(255, 255, 255));
        themhoadon.setText("Thêm Hóa Đơn");
        themhoadon.setPreferredSize(new java.awt.Dimension(110, 25));
        themhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themhoadonMouseClicked(evt);
            }
        });
        themhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themhoadonActionPerformed(evt);
            }
        });

        hoanthanhhoadon.setBackground(new java.awt.Color(0, 85, 0));
        hoanthanhhoadon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hoanthanhhoadon.setForeground(new java.awt.Color(255, 255, 255));
        hoanthanhhoadon.setText("Hoàn Thành");
        hoanthanhhoadon.setPreferredSize(new java.awt.Dimension(110, 25));
        hoanthanhhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoanthanhhoadonMouseClicked(evt);
            }
        });
        hoanthanhhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoanthanhhoadonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 85, 0));
        jLabel5.setText("Tên Khách Hàng");

        Mahoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MahoadonActionPerformed(evt);
            }
        });

        jDateNL.setDateFormatString("dd/MM/yyyy");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 85, 0));
        jLabel17.setText("Ngày Lập");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 85, 0));
        jLabel6.setText("Tình Trạng");

        tinhtrang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoàn Thành", "Chưa Hoàn Thành", "Đã Hủy", " " }));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 85, 0));
        jLabel18.setText("Ghi Chú");

        suahoadon.setBackground(new java.awt.Color(0, 85, 0));
        suahoadon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        suahoadon.setForeground(new java.awt.Color(255, 255, 255));
        suahoadon.setText("Sửa Hóa Đơn");
        suahoadon.setPreferredSize(new java.awt.Dimension(110, 25));
        suahoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suahoadonMouseClicked(evt);
            }
        });

        xoahoadon.setBackground(new java.awt.Color(110, 0, 0));
        xoahoadon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        xoahoadon.setForeground(new java.awt.Color(255, 255, 255));
        xoahoadon.setText("Xóa Hóa Đơn");
        xoahoadon.setPreferredSize(new java.awt.Dimension(110, 25));
        xoahoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoahoadonMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 85, 0));
        jLabel19.setText("Mã Hóa Đơn ");

        TenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenKhachHangActionPerformed(evt);
            }
        });

        Timkiem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tinhtrang, 0, 135, Short.MAX_VALUE)
                                    .addComponent(jDateNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hoanthanhhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(themhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(suahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xoahoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Timkiem2)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateNL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(themhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hoanthanhhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Timkiem2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xoahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 85, 0));
        jLabel11.setText("Giá Sản Phẩm");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 85, 0));
        jLabel13.setText("Mã Hóa Đơn");

        MaHoaDonTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaHoaDonTongTienActionPerformed(evt);
            }
        });
        MaHoaDonTongTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MaHoaDonTongTienKeyPressed(evt);
            }
        });

        in_hoa_don.setBackground(new java.awt.Color(0, 85, 0));
        in_hoa_don.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        in_hoa_don.setForeground(new java.awt.Color(255, 255, 255));
        in_hoa_don.setText("In Hóa Đơn");
        in_hoa_don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_hoa_donActionPerformed(evt);
            }
        });

        jBTTONGHD.setBackground(new java.awt.Color(0, 85, 0));
        jBTTONGHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBTTONGHD.setForeground(new java.awt.Color(255, 255, 255));
        jBTTONGHD.setText("Tổng Hóa Đơn");
        jBTTONGHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTTONGHDActionPerformed(evt);
            }
        });

        jTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTongTienActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Danh Sách Sản Phẩm");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Chi Tiết Hóa Đơn");

        Chitiethoadon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Chitiethoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        Chitiethoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChitiethoadonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ChitiethoadonMousePressed(evt);
            }
        });
        Chitiethoadon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ChitiethoadonKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(Chitiethoadon);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Danh Sách Hóa Đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(Thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(MaHoaDonTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(in_hoa_don)
                                .addGap(37, 37, 37)
                                .addComponent(jBTTONGHD, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTongTien)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Huy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Huy, Sua, Them, Xoa});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, jLabel8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MaHoaDonTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jBTTONGHD)
                                    .addComponent(in_hoa_don)
                                    .addComponent(jTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MaHD)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(GiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(SoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Huy, Sua, Them, Xoa});

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("_");
        jLabel2.setMaximumSize(new java.awt.Dimension(12, 19));
        jLabel2.setMinimumSize(new java.awt.Dimension(12, 19));
        jLabel2.setPreferredSize(new java.awt.Dimension(12, 19));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Gabriola", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CAND SNEAKER");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sp-icon.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nv-icon.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kh-icon.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hd-icon.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Nhân Viên");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 204, 204));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Khách Hàng");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 204, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Sản Phẩm");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 204, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Hóa Đơn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XoaMouseClicked
        // TODO add your handling code here:
        if (MaSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm cần xóa!");
        } else {
            try {

                int ketqua = JOptionPane.showConfirmDialog(this, "Xóa sản phẩm?", "Chú ý", JOptionPane.YES_NO_OPTION);
                if (ketqua == JOptionPane.YES_OPTION) {
                    String Masp = MaSP.getText();
                    String Query = "Delete from banhang.Hoadon where `Mã Sản Phẩm`=" + Masp;
                    Statement Add = Con.createStatement();
                    Add.executeUpdate(Query);
                    ChonHD();
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_XoaMouseClicked

    private void ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThemMouseClicked
        // TODO add your handling code here:
        if (Mahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập Thiếu Thông Tin!");
        } else {
            if (tinhtrang.getSelectedItem().toString() == "Hoàn Thành") {
                JOptionPane.showMessageDialog(this, "Không Thể Thay Đổi Hóa Đơn Đã Hoàn Thành", "Không Thể Xóa", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    Con = ClassData.ConnectDb();
                    int ketqua = JOptionPane.showConfirmDialog(this, "Thêm Sản Phẩm Vào Hóa Đơn?", "Chú ý", JOptionPane.YES_NO_OPTION);
                    if (ketqua == JOptionPane.YES_OPTION) {
                        PreparedStatement add = Con.prepareStatement("insert into Hoadon(`Mã Hóa Đơn`,`Mã Sản Phẩm`,`Số Lượng`,`Đơn Giá`,`Thành Tiền`) values(?,?,?,?,?)");
                        add.setInt(1, Integer.valueOf(MaHD.getText()));
                        add.setInt(2, Integer.valueOf(MaSP.getText()));
                        add.setInt(3, Integer.valueOf(SoSP.getText()));
                        add.setInt(4, Integer.valueOf(GiaSP.getText()));
                        add.setInt(5, Integer.valueOf(Thanhtien.getText()));
                        int row = add.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Thêm Sản Phẩm Thành Công!");
                        Con.close();
                        ChonHD();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_ThemMouseClicked

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemActionPerformed

    private void HuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuyMouseClicked
        // TODO add your handling code here:
        MaSP.setText("");
        SoSP.setText("");
        GiaSP.setText("");
        ChonSP();
    }//GEN-LAST:event_HuyMouseClicked

    private void SuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuaMouseClicked
        // TODO add your handling code here:

        if (MaHD.getText().isEmpty() || MaSP.getText().isEmpty() || SoSP.getText().isEmpty() || GiaSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy chọn sản phẩm cần sửa!");
        } else {
            try {
                Con = ClassData.ConnectDb();
                int ketqua = JOptionPane.showConfirmDialog(this, "Sửa thông tin sản phẩm?", "Chú ý", JOptionPane.YES_NO_OPTION);
                if (ketqua == JOptionPane.YES_OPTION) {
                    String Query = "Update banhang.Hoadon set `Số Lượng`='" + SoSP.getText() + "' where `Mã Sản Phẩm`=" + MaSP.getText();
                    Statement Add = Con.createStatement();
                    Add.executeUpdate(Query);
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sản phẩm thành công!");
                    ChonHD();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_SuaMouseClicked

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaActionPerformed

    private void BangSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangSPMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BangSP.getModel();
        int Myindex = BangSP.getSelectedRow();
        MaSP.setText(model.getValueAt(Myindex, 0).toString());
        GiaSP.setText(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_BangSPMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ChitiethoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitiethoadonMouseClicked
//
//        int row = Chitiethoadon.getSelectedRow();
//        if (row != -1) {
//            jMaHoaDon.setText(Chitiethoadon.getValueAt(row, 0).toString());
//            MaSP.setText(Chitiethoadon.getValueAt(row, 1).toString());
//            jSoLuong.setText(Chitiethoadon.getValueAt(row, 2).toString());
//
//        }
        DefaultTableModel model = (DefaultTableModel) Chitiethoadon.getModel();
        int Myindex = Chitiethoadon.getSelectedRow();
        MaHD.setText(model.getValueAt(Myindex, 0).toString());
        MaSP.setText(model.getValueAt(Myindex, 1).toString());
        SoSP.setText(model.getValueAt(Myindex, 2).toString());
        GiaSP.setText(model.getValueAt(Myindex, 3).toString());
        Thanhtien.setText(model.getValueAt(Myindex, 4).toString());


    }//GEN-LAST:event_ChitiethoadonMouseClicked

    private void themhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themhoadonActionPerformed
//        //        Them_hoa_don thd = new Them_hoa_don();
//        ThemHoaDon thd = new ThemHoaDon();
//        thd.setVisible(true);
//        thd.setSize(1024, 768);
//        thd.setLocationRelativeTo(null);

    }//GEN-LAST:event_themhoadonActionPerformed

    private void hoanthanhhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoanthanhhoadonActionPerformed
//        mhdht = MaHoaDonTongTien.getText();
//
//        java.util.Date ngaylap = Date.valueOf(ngaylaphoanhthanh);
//        SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
//        String ngaylap1 = format.format(ngaylap.getTime());
//        int hdhoanthanh = 0;
//
//        if (mhdht != null) {
//            String sql1 = "SELECT `hoanthanh` FROM `hoadon` WHERE `mahd`='" + mhdht + "'";
//            try {
//                stmt = conn.prepareStatement(sql1);
//                rs = stmt.executeQuery();
//                while (rs.next()) {
//                    hdhoanthanh = rs.getInt("hoanthanh");
//
//                }
//
//            } catch (SQLException ex) {
//                Logger.getLogger(Giaodienhoadon.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            if (hdhoanthanh == 1) {
//                JOptionPane.showMessageDialog(null, "Hóa đơn đã được giải quyết bạn không được quyền xử lí lại");
//
//            } else if (hdhoanthanh == 0) {
//                String sql = "UPDATE `hoadon` SET `mahd`='" + mhdht + "',`maadmin`='" + maadminhoanthanh + "'" + ",`ngaylap`='" + ngaylap1 + "',`ghichu`='" + "" + "',`tongtien`='" + 1 + "',`hoanthanh`='" + 1 + "' WHERE `mahd`=" + mhdht + "";
//                try {
//                    stmt = conn.prepareStatement(sql);
//                    int i = stmt.executeUpdate();
//                    if (i > 0) {
//                        JOptionPane.showMessageDialog(null, "Hoàn Thành");
//                        Giaodienhoadon giaodienhoadon = new Giaodienhoadon();
//                        giaodienhoadon.setSize(1024, 768);
//                        giaodienhoadon.setLocationRelativeTo(null);
//                        giaodienhoadon.setVisible(true);
//
//                        setNUll();
//
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Thất Bại");
//
//                    }
//
//                } catch (SQLException ex) {
//                    Logger.getLogger(Giaodienhoadon.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        } else if (mhdht == null) {
//            JOptionPane.showMessageDialog(null, "Hãy Chon Hóa Đơn Bạn Muốn Hoàn Thành");
//        }

    }//GEN-LAST:event_hoanthanhhoadonActionPerformed

    private void in_hoa_donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_hoa_donActionPerformed
//        inhoadon();
//        inhoadon.setSize(800, 800);
//
//        inhoadon.setLocationRelativeTo(null);
//        inhoadon.setVisible(true);

        //        String link = "D:\\New1\\QuanLyLapTop\\QuanLyLapTop\\src\\quanlylaptop\\report1.jrxml";
        //
        //        try {
        //            Class.forName("com.mysql.jdbc.Driver");
        //            Connection conn=DriverManager.getConnection("jdbc:mysql://Localhost/quanlysach", "root", "");
        //            JasperReport jr = JasperCompileManager.compileReport(link);
        //            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
        //            JasperViewer.viewReport(jp);
        //
        //
        //        } catch (Exception e) {
        //            e.printStackTrace();
        //        }
    }//GEN-LAST:event_in_hoa_donActionPerformed

    private void jBTTONGHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTTONGHDActionPerformed
        String mahd = MaHoaDonTongTien.getText().toString();

        String sql = "SELECT SUM(`Thành Tiền`) FROM `Hoadon` WHERE `Mã Hóa Đơn`=" + mahd + "";
        try {
            St = Con.prepareStatement(sql);
            Rs = St.executeQuery(sql);
            while (Rs.next()) {
                double giatongtamthoi = Rs.getDouble("SUM(`Thành Tiền`)");

                NumberFormat fm = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
                String trunggian = fm.format(giatongtamthoi);
                jTongTien.setText(trunggian);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jBTTONGHDActionPerformed

    private void DSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSHDMouseClicked

        DefaultTableModel model = (DefaultTableModel) DSHD.getModel();
        int Myindex = DSHD.getSelectedRow();
        Mahoadon.setText(model.getValueAt(Myindex, 0).toString());
        TenKhachHang.setText(model.getValueAt(Myindex, 1).toString());
        try {
            Date dt = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").parse((String) model.getValueAt(Myindex, 2));
            jDateNL.setDate(dt);
        } catch (Exception e) {
            e.printStackTrace();
        }
        tinhtrang.setSelectedItem(model.getValueAt(Myindex, 3).toString());
        ghichu.setText(model.getValueAt(Myindex, 4).toString());

//                try {
//            Con= ClassData.ConnectDb();
//            St = Con.createStatement();
//            Rs = St.executeQuery("Select MAX(`Mã Hóa Đơn`) AS id from banhang.Danhsachhoadon");
//            int lastid = Rs.getInt("id");
//            Mahoadon.setText(String.valueOf(lastid));
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

    }//GEN-LAST:event_DSHDMouseClicked

    private void themhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themhoadonMouseClicked
        // TODO add your handling code here:
        Date ngaylap = jDateNL.getDate();
        SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
        String ngaylap1 = format.format(ngaylap.getTime());
        if (Mahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập Thiếu Thông Tin!");
        } else {
            try {
                Con = ClassData.ConnectDb();
                int ketqua = JOptionPane.showConfirmDialog(this, "Thêm Hóa Đơn Vào Danh Sách?", "Chú ý", JOptionPane.YES_NO_OPTION);
                if (ketqua == JOptionPane.YES_OPTION) {
                    PreparedStatement add = Con.prepareStatement("insert into Danhsachhoadon values(?,?,?,?,?)");
                    add.setInt(1, Integer.valueOf(Mahoadon.getText()));
                    add.setString(2, ngaylap1);
                    add.setString(3, TenKhachHang.getText());
                    add.setString(4, tinhtrang.getSelectedItem().toString());
                    add.setString(5, ghichu.getText());
                    int row = add.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thêm Hóa Đơn Thành Công!");
                    Con.close();
                    ChonDSHD();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_themhoadonMouseClicked

    private void xoahoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoahoadonMouseClicked
        // TODO add your handling code here:
        if (Mahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chọn hóa đơn cần xóa!");
        } else {
            if (tinhtrang.getSelectedItem().toString() == "Hoàn Thành") {
                JOptionPane.showMessageDialog(this, "Không Thể Xóa Hóa Đơn Đã Hoàn Thành", "Không Thể Xóa", JOptionPane.ERROR_MESSAGE);

            } else {
                try {
                    Con = ClassData.ConnectDb();
                    int ketqua = JOptionPane.showConfirmDialog(this, "Xóa Hóa Đơn Khỏi Danh Sách?", "Chú ý", JOptionPane.YES_NO_OPTION);
                    if (ketqua == JOptionPane.YES_OPTION) {
                        String Mahd = Mahoadon.getText();
                        String Query = "Delete from banhang.Danhsachhoadon where `Mã Hóa Đơn`=" + Mahd;
                        Statement Add = Con.createStatement();
                        Add.executeUpdate(Query);
                        ChonDSHD();
                        JOptionPane.showMessageDialog(this, "Xóa Hóa Đơn Thành Công!");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_xoahoadonMouseClicked

    private void hoanthanhhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoanthanhhoadonMouseClicked
        // TODO add your handling code here:
        if (Mahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chọn Hóa Đơn!");
        } else {
            if (tinhtrang.getSelectedItem().toString() == "Hoàn Thành") {
                JOptionPane.showMessageDialog(this, "Hóa Đơn Đã Được Hoàn Thành", "Chú Ý", JOptionPane.ERROR_MESSAGE);
            } else if (tinhtrang.getSelectedItem().toString() == "Đã Hủy") {
                JOptionPane.showMessageDialog(this, "Hóa Đơn Đã Bị Hủy", "Chú Ý", JOptionPane.ERROR_MESSAGE);
            } else {
                tinhtrang.setSelectedIndex(0);
                try {
                    Con = ClassData.ConnectDb();
                    int ketqua = JOptionPane.showConfirmDialog(this, "Hoàn Thành Đơn Hàng?", "Chú ý", JOptionPane.YES_NO_OPTION);
                    if (ketqua == JOptionPane.YES_OPTION) {
                        String Query = "Update banhang.Danhsachhoadon set `Tình Trạng`='" + tinhtrang.getSelectedItem().toString() + "'where `Mã Hóa Đơn`= " + Mahoadon.getText();
                        Statement Add = Con.createStatement();
                        Add.executeUpdate(Query);
                        JOptionPane.showMessageDialog(this, "Đã Hoàn Thành Đơn Hàng!");
                        ChonDSHD();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_hoanthanhhoadonMouseClicked

    private void MaHoaDonTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaHoaDonTongTienActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_MaHoaDonTongTienActionPerformed

    private void MaHoaDonTongTienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaHoaDonTongTienKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (MaHoaDonTongTien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Chưa Nhập Mã Hóa Đơn");
            } else {
                try {
                    Con = ClassData.ConnectDb();
                    String tk = MaHoaDonTongTien.getText();
                    St = Con.createStatement();
                    Rs = St.executeQuery("Select * from banhang.Hoadon where `Mã Hóa Đơn` like '" + tk + "' ");
                    Chitiethoadon.setModel(DbUtils.resultSetToTableModel((Rs)));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }


    }//GEN-LAST:event_MaHoaDonTongTienKeyPressed

    private void MaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaHDActionPerformed
        // TODO add your handling code here:
        MaHD.setText(MaHoaDonTongTien.getText());
    }//GEN-LAST:event_MaHDActionPerformed

    private void MaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaSPActionPerformed

    private void DSHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSHDMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            MaHoaDonTongTien.setText(Mahoadon.getText());
            MaHD.setText(Mahoadon.getText());
            ChonHD();
        }
        DSHD.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_DSHDMousePressed

    private void suahoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suahoadonMouseClicked
        // TODO add your handling code here:
        Con = ClassData.ConnectDb();
        try {
            String tk = MaHD.getText();
            St = Con.createStatement();
            Rs = St.executeQuery("Select `Tình Trạng` from banhang.hoadon where `Mã Hóa Đơn` like '" + tk + "'");
            while (Rs.next()) {
                String a = Rs.toString();
                if(a == "Hoàn Thành"){
                   JOptionPane.showMessageDialog(this, "Hóa Đơn Đã Hoàn Thành", "Chú Ý", JOptionPane.ERROR_MESSAGE);

                }
                   }
        }catch (Exception e) {
            e.printStackTrace();
        }     
        
        if (Mahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy chọn đơn hàng!");
        } else {
            if (tinhtrang.getSelectedItem().toString() == "Đã Hủy") {
                JOptionPane.showMessageDialog(this, "Hóa Đơn Đã Bị Hủy", "Chú Ý", JOptionPane.ERROR_MESSAGE);
            } else {
                
//                if (a == "Hoàn Thành") { //tinhtrang.getSelectedItem().toString()
//                JOptionPane.showMessageDialog(this, "Hóa Đơn Đã Hoàn Thành", "Chú Ý", JOptionPane.ERROR_MESSAGE);
//            } else {
{
                try {
                    Con = ClassData.ConnectDb();
                    int ketqua = JOptionPane.showConfirmDialog(this, "Sửa Thông Tin Hóa Đơn?", "Chú ý", JOptionPane.YES_NO_OPTION);
                    if (ketqua == JOptionPane.YES_OPTION) {
                        String Query = "Update banhang.Danhsachhoadon set `Ghi Chú`='" + ghichu.getText() + "',`Tình Trạng`='" + tinhtrang.getSelectedItem().toString() + "' where `Mã Hóa Đơn`=" + Mahoadon.getText();
                        Statement Add = Con.createStatement();
                        Add.executeUpdate(Query);
                        JOptionPane.showMessageDialog(this, "Sửa Thông Tin Hóa Đơn Thành Công!");
                        ChonDSHD();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        }
    }//GEN-LAST:event_suahoadonMouseClicked

    private void SoSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoSPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Con = ClassData.ConnectDb();

            try {
                String tk = MaSP.getText();
                St = Con.createStatement();
                Rs = St.executeQuery("Select * from banhang.sanpham where `Mã Sản Phẩm` like '" + tk + "'");
                Rs.next();
                if (Integer.parseInt(Rs.getString("Số Lượng")) < Integer.parseInt(SoSP.getText().toString())) {
                    JOptionPane.showMessageDialog(this, "Không Đủ Số Lượng Hàng");
                } else {
                    String gia = GiaSP.getText().toString();
                    String so = SoSP.getText().toString();
                    int a = Integer.parseInt(gia);
                    int b = Integer.parseInt(so);
//            NumberFormat fm = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
//            String trunggian = fm.format(a * b);
                    Thanhtien.setText((String.valueOf(a * b)));//String.valueOf(trunggian)); 
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_SoSPKeyPressed

    private void SoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoSPActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SoSPActionPerformed

    private void GiaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GiaSPActionPerformed

    private void ChitiethoadonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitiethoadonMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 1 && !evt.isConsumed()) {
            evt.consume();
            Chitiethoadon.setDefaultEditor(Object.class, null);
        }
    }//GEN-LAST:event_ChitiethoadonMousePressed

    private void jTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTongTienActionPerformed

    private void DSHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DSHDKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            DefaultTableModel model = (DefaultTableModel) DSHD.getModel();
            int Myindex = DSHD.getSelectedRow();
            Mahoadon.setText(model.getValueAt(Myindex, 0).toString());
            try {
                Date dt = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").parse((String) model.getValueAt(Myindex, 1));
                jDateNL.setDate(dt);
            } catch (Exception e) {
                e.printStackTrace();
            }
            tinhtrang.setSelectedItem(model.getValueAt(Myindex, 2).toString());
            ghichu.setText(model.getValueAt(Myindex, 3).toString());
        }
    }//GEN-LAST:event_DSHDKeyReleased

    private void ChitiethoadonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChitiethoadonKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            DefaultTableModel model = (DefaultTableModel) Chitiethoadon.getModel();
            int Myindex = Chitiethoadon.getSelectedRow();
            MaHD.setText(model.getValueAt(Myindex, 0).toString());
            MaSP.setText(model.getValueAt(Myindex, 1).toString());
            SoSP.setText(model.getValueAt(Myindex, 2).toString());
            GiaSP.setText(model.getValueAt(Myindex, 3).toString());
        }

    }//GEN-LAST:event_ChitiethoadonKeyReleased

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XoaActionPerformed

    private void MahoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MahoadonActionPerformed
        // TODO add your handling code here:
        try {
            Con = ClassData.ConnectDb();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * MAX(`Mã Hóa Đơn`) from banhang.Danhsachhoadon");
            Mahoadon.setText(Rs.getString(0));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_MahoadonActionPerformed

    private void BangSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangSPMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 1 && !evt.isConsumed()) {
            evt.consume();
            BangSP.setDefaultEditor(Object.class, null);
        }
    }//GEN-LAST:event_BangSPMousePressed

    private void GiaSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GiaSPKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_GiaSPKeyPressed

    private void MaSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaSPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (MaSP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nhap thong tin tim kiem");
            } else {
                try {
                    Con = ClassData.ConnectDb();
                    String tk = MaSP.getText();
                    St = Con.createStatement();
                    Rs = St.executeQuery("Select * from banhang.Sanpham where `Mã Sản Phẩm` like '" + tk + "'");
                    BangSP.setModel(DbUtils.resultSetToTableModel((Rs)));
//                    DefaultTableModel model = (DefaultTableModel) BangSP.getModel();
//                    int Myindex = BangSP.getSelectedRow();
//                    GiaSP.setText(model.getValueAt(Myindex,4).toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_MaSPKeyPressed

    private void TenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenKhachHangActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
                   new Seller().setVisible(true);
                   this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangSP;
    private javax.swing.JTable Chitiethoadon;
    private javax.swing.JTable DSHD;
    private javax.swing.JTextField GiaSP;
    private javax.swing.JButton Huy;
    private javax.swing.JTextField MaHD;
    private javax.swing.JTextField MaHoaDonTongTien;
    private javax.swing.JTextField MaSP;
    private javax.swing.JTextField Mahoadon;
    private javax.swing.JTextField SoSP;
    private javax.swing.JButton Sua;
    private javax.swing.JTextField TenKhachHang;
    private javax.swing.JTextField Thanhtien;
    private javax.swing.JButton Them;
    private javax.swing.JTextField Timkiem2;
    private javax.swing.JButton Xoa;
    private javax.swing.JTextField ghichu;
    private javax.swing.JButton hoanthanhhoadon;
    private javax.swing.JButton in_hoa_don;
    private javax.swing.JButton jBTTONGHD;
    private com.toedter.calendar.JDateChooser jDateNL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTongTien;
    private javax.swing.JButton suahoadon;
    private javax.swing.JButton themhoadon;
    private javax.swing.JComboBox<String> tinhtrang;
    private javax.swing.JButton xoahoadon;
    // End of variables declaration//GEN-END:variables
}
